In [3]:
import numpy as np

## Sorting

In [4]:
unsorted = np.array([3,1,2,1,4,7,5,6])
print("Sorted array: ",np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1,2],[6,4,5]])
print("2D Sorted array along axis 0:\n",np.sort(arr_2d_unsorted, axis=0))
print("2D Sorted array along axis 1:\n",np.sort(arr_2d_unsorted, axis=1))

Sorted array:  [1 1 2 3 4 5 6 7]
2D Sorted array along axis 0:
 [[3 1 2]
 [6 4 5]]
2D Sorted array along axis 1:
 [[1 2 3]
 [4 5 6]]


## Filter

In [5]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[numbers %2 ==0]
print("Even Numbers: ", even_numbers)

Even Numbers:  [ 2  4  6  8 10]


## Filter With Mask

In [6]:
mask = numbers > 5
print("Numbers greater than 5: ",numbers[mask])

Numbers greater than 5:  [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [9]:
indices = np.array([0,3,5])
print(numbers[indices])

where_result = np.where(numbers>5)
print(where_result)
print("NP where: ",numbers[where_result])

[1 4 6]
(array([5, 6, 7, 8, 9]),)
NP where:  [ 6  7  8  9 10]


In [14]:
condition_array = np.where(numbers>5, numbers*2, numbers)
print(condition_array)
condition_array_2 = np.where(numbers>5, "True", "False")
print(condition_array_2)

[ 1  2  3  4  5 12 14 16 18 20]
['False' 'False' 'False' 'False' 'False' 'True' 'True' 'True' 'True'
 'True']


## Adding and Removing Data

In [21]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


## Array compatibility

In [24]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("Compatibility shapes: ", a.shape == b.shape)

Compatibility shapes:  True


In [32]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original, new_row))
print(with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((new_col, original))
print(with_new_col)

[[1 2]
 [3 4]
 [5 6]]
[[7 1 2]
 [8 3 4]]
