## Advance Operation with Business Example

In [3]:
import numpy as np
import matplotlib as plt

In [ ]:
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

print("==== Zomato sales analysis ==== ")
print("\n Sales data shapes", sales_data.shape)
print("\n Sample data for 1st three restaurant: \n",sales_data[:3, 1:])

==== Zomato sales analysis ==== 

 Sales data shapes (5, 5)

 Sample data for 1st three restaurant: 
 [[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]]


In [5]:
# total sales per year
print(np.sum(sales_data, axis=0))

[     15  810000  945000 1085000 1240000]
