## Numpy array and basics
learn about numpy

In [2]:
import numpy as np

In [9]:
import numpy as np
array_1d = np.array([1,2,3,4,5])
print("1D Array:", array_1d)


1D Array: [1 2 3 4 5]


In [6]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print("Array:", arr)
print(arr[::-1])

Array: [1 2 3 4 5 6]
[6 5 4 3 2 1]


In [8]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Original Array:\n", arr)
arr1 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix:\n", arr1)

Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
zeros = np.zeros((3,3))
print("Zeros Array:\n", zeros)

ones = np.ones((2,4))
print("Ones Array:\n", ones)

full = np.full((2,3),7)
print("Full Array:\n", full)

random = np.random.random((3,3))
print("Random Array:\n", random)

sequence = np.arange(0,10,2)
print("Sequence Array:", sequence)

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full Array:
 [[7 7 7]
 [7 7 7]]
Random Array:
 [[0.68328149 0.28524798 0.45028085]
 [0.60772669 0.48759259 0.60687953]
 [0.60875686 0.40615156 0.14074178]]
Sequence Array: [0 2 4 6 8]


### Vector ,Matrix and Tensor

In [ ]:
vector = np.array([1,2,3,4,5])
print("Original Vector:", vector)

matrix = np.array([[2,3], [5,4]])
print("Matrix:\n", matrix)

tensor = np.array([[[1,2], [3,4]],
                [[5,6], [7,8]]])
print("Tensor:\n", tensor)

Original Vector: [1 2 3 4 5]
Matrix:
 [[2 3]
 [5 4]]
Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [25]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])
print("Array shape: ", arr.shape)
print("Dimensions: ",arr.ndim)
print("Size: ", arr.size)
print("Data type: ", arr.dtype)


Array shape:  (2, 3)
Dimensions:  2
Size:  6
Data type:  int64


### Array Reshaping

In [8]:
arr = np.arange(12)
print("Array:", arr)

reshaped = arr.reshape((3,4))
print("Reshaped Array (3x4):\n", reshaped)

flattened = reshaped.flatten()
print("Flattened Array:", flattened)

# ravel (returns view, instead of copies)
raveled = reshaped.ravel()
print("Raveled Array:", raveled)

#Transpose
transposed = reshaped.T
print("Transposed Array:\n", transposed)

Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed Array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
